spring:
  application:
    name: jmqtt
#  profiles:
#    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /
logging:
  config: classpath:logback-console.xml
#swagger API
springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/api-docs

